#! /bin/sh

echo -n Running auto-tools "  " 

aclocal > /dev/null 2>&1 && echo -n . \
&& automake --foreign --add-missing --copy && echo -n . \
&& autoconf

echo
echo done
echo Please run ./configure
